version: "2.2"
services: 
  api:
    container_name: swtdisp-ap1-gr10-backend
    image: "elgaard1/api"
    ports:
      - "5000:80"
    depends_on:
      - db
    restart: always

  db:
    container_name: swtdisp-ap1-gr10-database
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "secretPassword1!"
      ACCEPT_EULA: "Y"

  gui:
    container_name: swtdisp-ap1-gr10-frontend
    image: "elgaard1/frontendproject"
    ports:
        - 9000:80
        - 9001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    