apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: swtdisp-ap1-gr10
  name: swtdisp-grp10-frontend
  labels:
    app: swtdisp-grp10-frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-pod

  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-pod

    spec:
      containers:
        - name: swtdisp-grp10-frontend-container
          image: elgaard1/frontendproject
          ports:
            - containerPort: 80 