version: "1"
services: 
  api:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    container_name: sql-server-db 
    image: "mcr.microsoft.com/mssql/server:latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
  gui:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    